### ISSUE TITLE
Documentation request - put the properties (/vm args) into the readme file

### ISSUE THREAD

**Issue by NateAustin** [PokeMMO/gdx-dbgagent#1]
Thanks so much for making this! When I'm using it from my IDE, the GL_Thread inspection created a ton of spam. I was able to find the property to use to turn it off by poking around in the source code, but it would be nice to have those listed with the features/usage instructions in the readme. Thanks again!

**Comment by PokeMMO** [comment]
Sure, sounds like a good addition to the documentation, I'll add it when I get some free time.

It also sounds like the GL_THREAD util isn't working correctly for you, which IDE and platform?

**Comment by NateAustin** [comment]
IntelliJ on Windows 10
