### ISSUE TITLE
False positives for Cubemap?

### ISSUE THREAD

**Issue by NateAustin** [PokeMMO/gdx-dbgagent#2]
I'm seeing what seems to be false positives for Cubemap - I'm correctly disposing it but it's reported as undisposed. I see that you have some special case code for Texture, but not for Cubemap, though both are subclasses of GLTexture. Is a special case needed for Cubemap too?

**Comment by PokeMMO** [comment]
It looks like it, Both Texture#dispose and Cubemap#dispose call GLTexture#delete directly instead of calling super.dispose.

I'll add an exception for Cubemap. It might also be good to make a PR for libgdx to call super.dispose instead of delete.
